config/routes.rb
Rails.application.routes.draw do

  resources :pictures
  resources :comments do
    collection do
      get :show_all_comments
    end
  end

end

app/models/comment.rb
class Comment

  include DataMapper::Resource

  property :id, Serial
  property :message, Text
  
  belongs_to :picture

  after :save, :add_to_elastic_index

	def add_to_elastic_index
		client = Comment.initiate_client
		client.index  index: 'code_challange', type: 'comment', id: self.id, body: picture.to_json(only: [:id, :title, :description])
	end

	def self.initiate_client
		Elasticsearch::Client.new log: true
	end

	def self.get_indexed_comments(picture_id)
		client = initiate_client
		response = client.search index: 'code_challange', type: 'comment', body: { query: { match: { id: picture_id } } }
		result = Hashie::Mash.new response
		comments_objects = result.hits.hits.map { |obj| Comment.get(obj['_id'].to_i) }
	end
end

app/models/picture.rb
require 'carrierwave/datamapper'
class Picture
  
  include DataMapper::Resource
  include DataMapper::Validate

  property :id, Serial
  property :title, String
  property :description, String
  
  mount_uploader :image, ImageUploader

  validates_presence_of :image

  has n, :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end

  def create
  	@comment = Comment.new(params[:comment])
    @picture = @comment.picture
    respond_to do |format|
      if @comment.save
        format.html { redirect_to pictures_path}
        format.js  {}
      end
    end
  end

  def show_all_comments
    @comments = Comment.get_indexed_comments(params[:picture_id])
    respond_to do |format|
        format.js  
      end
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
  	@pictures = Picture.paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(params[:picture])
    if @picture.save
      flash[:success] = "Picture Created Successfully"
      redirect_to pictures_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @picture = Picture.get(params[:id])
    @picture.comments << @comment
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/comments/_comments.html.haml
%br
- if @comments.length > 0
  %ul.list-group
    - @comments.each do |comment|
      %li.list-group-item
        = comment.message
- else
  %div.alert.alert-info
    "No Comments Posted Yet..."

app/views/comments/_form.html.haml
.col-md-12
  .commentForm{:style => "margin: 20px;"}
    = form_for @comment, :html => {:class => "form-horizontal"}, :remote => true do |f|
      .form-group
        = f.text_area :message, :class => "form-control", :rows => 3,  :placeholder => 'Comment here'
      = f.hidden_field :picture_id
      .form-group  
        = f.submit :class => "btn btn-primary btn-block"

app/views/comments/_list_comments.html.haml
.col-md-12
  #listAllComments
    %h2
      Loading Comments Please Wait ...

app/views/comments/create.js.erb
$(".commentForm").html("<div class='alert alert-success'> Your Comment Have been saved successfully !!!</div> ")

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/show_all_comments.js.erb
$("#listAllComments").html("<%= escape_javascript( render(:partial => 'comments/comments'))%>");

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %head
      %title CodeChallange
      = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
      = javascript_include_tag 'application', 'data-turbolinks-track' => true
      %script{:src => "https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"}
      = csrf_meta_tags
  %body{"data-controller" => controller.controller_name , "data-action" => controller.action_name }
    .container
      .header
        %ul.nav.nav-pills.pull-right
          %li.pictures_index
            = link_to 'Pictures', pictures_path
          %li.pictures_new
            = link_to 'New Picture', new_picture_path
          %li
            = mail_to 'rajesh.13kits@gmail.com', 'Hire Me ;) '
        %h3.text-muted Code Challenge
      %br
      .panel.alert.alert-info
        %h1 Meetyl 
        %p.lead Interview Follow-up: Code Challenge.

      = yield

      = javascript_include_tag 'tabajaxed', 'data-turbolinks-track' => true
      .clearfix
      .div{:style => "padding:100px;"}

app/views/pictures/_form.html.haml
= form_for @picture, :html => {:class => "form-horizontal"} do |f|
  .form-group
    %label.col-sm-2.control-label{:for => "title"} Title
    .col-sm-10
      = f.text_field :title, :placeholder => 'Title', :class => "form-control"
  .form-group
    %label.col-sm-2.control-label{:for => "description"} Description
    .col-sm-10
      = f.text_field :description, :placeholder => 'Description', :class => "form-control"
  .form-group
    %label.col-sm-2.control-label{:for => "description"} Image
    .col-sm-10
      = f.file_field :image, :class => "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit :class => 'submit btn btn-primary btn-block'

app/views/pictures/index.html.haml
%h2
  %center Pictures
.row
  - @pictures.each do |picture|
    .col-md-2
      .thumbnail
        = image_tag picture.image_url(:thumb) if picture.image?
        .caption
          %h3= picture.title
          %p
            = picture.description
          = link_to 'Show', picture_path(picture), :class => 'btn btn-primary'
= will_paginate @pictures

app/views/pictures/new.html.haml
.col-md-11
  = render 'form'

app/views/pictures/show.html.haml
.col-md-12
  %center
    = image_tag @picture.image_url(:original), :class => "img-thumbnail", :id => "MainImage", :data =>{"picture-id" => @picture.id}

.col-md-12{:style => "margin-top: 50px;"}
  %center
    .col-md-12
      %ul#myTab.nav.nav-tabs{:role => "tablist"}
        %li.active
          %a{"data-toggle" => "tab", :href => "#home", :role => "tab"} Comment
        %li
          %a{"data-toggle" => "tab", :href => "#profile", :role => "tab"} View All Comments
 
.tab-content{:style => "margin: 50px 0px 0px 10px;"}
  #home.tab-pane.active
    .clearfix
    = render :partial => "/comments/form"
  #profile.tab-pane
    = render :partial => "/comments/list_comments"